compatibility_date = "2024-08-15"

[build]
command = "cd frontend && npm ci && npm run build"
publish = "frontend/build"

[build.environment]
REACT_APP_API_URL = "https://your-backend.vercel.app/api"
REACT_APP_STRIPE_PUBLIC_KEY = ""

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[compatibility_flags]
nodejs_compat = true
