name = "travelling-website"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "travelling-website-db"
database_id = "b0fd9bb8-ca9a-4ca7-a2d0-487618098a3a"

# R2 Storage Configuration
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "travelling-website-images"

[assets]
directory = "./frontend/build"

[build]
command = "cd frontend && npm ci && npm run build"

[env.production.vars]
REACT_APP_API_URL = "https://travelling-website-mu.vercel.app/api"
REACT_APP_STRIPE_PUBLIC_KEY = ""

# Custom domain routes for phongphan.me (without wildcards)
[[routes]]
pattern = "phongphan.me"
custom_domain = true

[[routes]]
pattern = "www.phongphan.me"
custom_domain = true
