compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd frontend && npm ci && npm run build"

[env.production.vars]
REACT_APP_API_URL = "https://your-backend.vercel.app/api"
REACT_APP_STRIPE_PUBLIC_KEY = ""

[[routes]]
pattern = "/*"
custom_domain = true
