import React from 'react';
import {
  FiUser,
  FiMail,
  FiLock,
  FiEye,
  FiEyeOff,
  FiPhone,
  FiMapPin,
  FiCalendar,
  FiClock,
  FiUsers,
  FiStar,
  FiFilter,
  FiSearch,
  FiGrid,
  FiList,
  FiMenu,
  FiX,
  FiLogOut,
  FiSettings,
  FiEdit3,
  FiSave,
  FiCheck,
  FiCamera,
  FiPlay,
  FiArrowRight,
  FiCreditCard,
  FiDownload,
  FiBarChart,
  FiFacebook,
  FiInstagram,
  FiTwitter,
  FiPlus,
  FiTrash2,
  FiSun,
  FiMoon,
  FiChevronDown,
  FiDollarSign,
} from 'react-icons/fi';
import { IconType } from 'react-icons';

// Create a wrapper component for icons that works with IconType
interface IconProps {
  icon: IconType;
  className?: string;
  onClick?: () => void;
  size?: number;
}

export const Icon: React.FC<IconProps> = ({ icon: IconComponent, className, onClick, size }) => {
  return React.createElement(IconComponent as React.ComponentType<any>, { className, onClick, size });
};

// Export icons directly from react-icons/fi
export {
  FiUser,
  FiMail,
  FiLock,
  FiEye,
  FiEyeOff,
  FiPhone,
  FiMapPin,
  FiCalendar,
  FiClock,
  FiUsers,
  FiStar,
  FiFilter,
  FiSearch,
  FiGrid,
  FiList,
  FiMenu,
  FiX,
  FiLogOut,
  FiSettings,
  FiEdit3,
  FiSave,
  FiCheck,
  FiCamera,
  FiPlay,
  FiArrowRight,
  FiCreditCard,
  FiDownload,
  FiBarChart,
  FiFacebook,
  FiInstagram,
  FiTwitter,
  FiPlus,
  FiTrash2,
  FiSun,
  FiMoon,
  FiChevronDown,
  FiDollarSign,
};

// Export an object with all icons for easier imports
export const Icons = {
  FiUser,
  FiMail,
  FiLock,
  FiEye,
  FiEyeOff,
  FiPhone,
  FiMapPin,
  FiCalendar,
  FiClock,
  FiUsers,
  FiStar,
  FiFilter,
  FiSearch,
  FiGrid,
  FiList,
  FiMenu,
  FiX,
  FiLogOut,
  FiSettings,
  FiEdit3,
  FiSave,
  FiCheck,
  FiCamera,
  FiPlay,
  FiArrowRight,
  FiCreditCard,
  FiDownload,
  FiBarChart,
  FiFacebook,
  FiInstagram,
  FiTwitter,
  FiPlus,
  FiTrash2,
  FiSun,
  FiMoon,
  FiChevronDown,
  FiDollarSign,
};
